from __future__ import annotations

from security.permissions.dto import PermissionCheckResult
from security.permissions.enums import (
    PermissionAction,
    PermissionDeniedReason,
    PermissionErrorCode,
)
from security.permissions.exceptions import PermissionCheckError, PermissionDeniedError
from security.permissions.protocols import (
    SupportsNode,
    SupportsNodePermission,
    SupportsUser,
)
from security.permissions.service import (
    ACTION_REQUIRED_PERMISSION_LEVEL,
    PERMISSION_LEVEL_PRIORITY,
    can_delete_node,
    can_download_node,
    can_manage_node,
    can_read_node,
    can_share_node,
    can_write_node,
    check_node_permission,
    find_user_permission,
    is_active_user,
    is_admin_user,
    is_node_owner,
    is_regular_user,
    permission_allows_action,
    permission_is_active_at,
    permission_level_allows_action,
    permission_level_at_least,
    public_node_allows_action,
    require_active_user,
    require_admin,
    require_node_permission,
    resolve_permission_denied_reason,
)
from security.permissions.validators import (
    get_object_uuid,
    get_optional_user_id,
    normalize_moment,
    normalize_node_visibility,
    normalize_permission_action,
    normalize_permission_level,
)

__all__ = [
    "PermissionAction",
    "PermissionDeniedReason",
    "PermissionErrorCode",
    "PermissionCheckError",
    "PermissionDeniedError",
    "PermissionCheckResult",
    "SupportsUser",
    "SupportsNode",
    "SupportsNodePermission",
    "PERMISSION_LEVEL_PRIORITY",
    "ACTION_REQUIRED_PERMISSION_LEVEL",
    "check_node_permission",
    "require_node_permission",
    "can_read_node",
    "can_download_node",
    "can_write_node",
    "can_delete_node",
    "can_share_node",
    "can_manage_node",
    "require_admin",
    "require_active_user",
    "is_active_user",
    "is_admin_user",
    "is_regular_user",
    "is_node_owner",
    "public_node_allows_action",
    "permission_allows_action",
    "permission_level_allows_action",
    "permission_level_at_least",
    "find_user_permission",
    "permission_is_active_at",
    "resolve_permission_denied_reason",
    "normalize_permission_action",
    "normalize_permission_level",
    "normalize_node_visibility",
    "get_object_uuid",
    "get_optional_user_id",
    "normalize_moment",
]
